browser = chrome
URL_1 = https://testautomationpractice.blogspot.com
URL_2 = https://www.amazon.in/
driverProperty = webdriver.chrome.driver
driverPath = C:\\Users\\bawas\\eclipse-workspace\\
ExcelheetName = sheet1
log4jPropertiesFileLoc = C:\\Users\\bawas\\eclipse-workspace\\Java\\test-output\\log4j.properties
